version: "3.8"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: vristo
  mysql_db:
    image: "mysql:8.0.32"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: vristo
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
